# -*- coding: utf-8 -*-
"""Python Essentials.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dut2fBI4CpBpKdKThvXz7U2KXua3pEPy
"""

#Exemplo 1 - Print

print("Olá, meu nome é Ana Julia.")

#Exemplo 2 - Média altura

print("Esse programa irá calcular a média de altura de 5 pessoas.")

altura_1 = float(input("Digite a altura da primeira pessoa: "))
altura_2 = float(input("Digite a altura da segunda pessoa: "))
altura_3 = float(input("Digite a altura da terceira pessoa: "))
altura_4 = float(input("Digite a altura da quarta pessoa: "))
altura_5 = float(input("Digite a altura da quinta pessoa: "))

media_altura = (altura_1 + altura_2 + altura_3 + altura_4 + altura_5) / 5

print ("A média de altura é: ", media_altura)

#Exemplo 3 - Importar biblioteca math

import math

print("A raiz quadrada de 9 é:",math.sqrt(9))

print("A área de circunferencia de raiz 2 é:", math.pi * math.pow(2,2))

# Exemplo 4 - Função

print("Sirius Black")
print("Shawn" , "Mendes")

print("shawn\nmendes")

print("Meu", "nome", "é", "Ana", "Julia", sep="-")

print("ana ", " julia", sep=",")

print("Greg\'s book.")
print("'Greg's book.'")
print("Greg\'s book.")
print("Greg\'s book.")
print("Greg's book.")

print("Eu", "vou" \n )